- filename: DBLP.bib
  search_type: FEED
  source_name: Hawaii International Conference on System Sciences
  source_url: ''
  search_parameters:
  - endpoint: dblp
    params: SCOPE venue_key='conf/hicss' AND journal_abbreviated='hicss'
  last_sync: null
  comment: ''
  outlet: null
  sub_dir_pattern: null
- filename: pdfs.bib
  search_type: PDFS
  source_name: HCISS
  source_url: pdfs
  search_parameters: NA
  last_sync: null
  comment: NA
  outlet: conference=Hawaii International Conference on System Sciences
  sub_dir_pattern: year
- filename: CROSSREF.bib
  search_type: FEED
  source_name: CROSSREF
  source_url: CROSSREF.bib
  search_parameters: ''
  last_sync: null
  comment: ''
  outlet: null
  sub_dir_pattern: null
